"""Backend-rendered PDF strings (EN/ES).

Mirrors the keys consumed by case_file.html. Kept as plain dicts (no gettext)
because the PDF renderer is the only consumer and the set is small + stable.
"""

PDF_STRINGS = {
    "en": {
        "cover_title": "Case File",
        "generated_on": "Generated on",
        "total_exhibits": "Total exhibits",
        "generated_by": "Generated by Social Monitor",
        "index": "Index of Exhibits",
        "exhibit": "Exhibit",
        "of": "of",
        "page": "Page",
        "platform": "Platform",
        "username": "Username",
        "posted": "Posted",
        "captured": "Captured",
        "post_url": "Post URL",
        "sha256": "SHA-256",
        "md5": "MD5",
        "mhtml_captured": "MHTML archive",
        "hashes_computed": "Hashes verified",
        "yes": "Yes",
        "no": "No",
        "text_content": "Post content",
        "screenshot": "Screenshot",
        "notes": "Analyst notes",
        "no_notes": "(no notes recorded)",
        "engagement": "Engagement",
        "likes": "Likes",
        "shares": "Shares",
        "comments": "Comments",
        "views": "Views",
        "added": "Added",
        "set_description": "Description",
        "no_screenshot": "(screenshot unavailable)",
    },
    "es": {
        "cover_title": "Expediente",
        "generated_on": "Generado el",
        "total_exhibits": "Total de elementos",
        "generated_by": "Generado por Monitor Social",
        "index": "Índice de elementos",
        "exhibit": "Elemento",
        "of": "de",
        "page": "Página",
        "platform": "Plataforma",
        "username": "Usuario",
        "posted": "Publicado",
        "captured": "Capturado",
        "post_url": "URL de la publicación",
        "sha256": "SHA-256",
        "md5": "MD5",
        "mhtml_captured": "Archivo MHTML",
        "hashes_computed": "Hashes verificados",
        "yes": "Sí",
        "no": "No",
        "text_content": "Contenido de la publicación",
        "screenshot": "Captura de pantalla",
        "notes": "Notas del analista",
        "no_notes": "(sin notas registradas)",
        "engagement": "Interacción",
        "likes": "Me gusta",
        "shares": "Compartidos",
        "comments": "Comentarios",
        "views": "Vistas",
        "added": "Añadido",
        "set_description": "Descripción",
        "no_screenshot": "(captura no disponible)",
    },
}


def get_pdf_strings(locale: str) -> dict:
    """Return the string table for `locale`, falling back to English."""
    return PDF_STRINGS.get(locale, PDF_STRINGS["en"])
